// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkp80OWvDjT5izvKBJwtbSJ_4cnRKrhEU',
    appId: '1:1017556164170:web:63ad4745b969c4273b10b3',
    messagingSenderId: '1017556164170',
    projectId: 'book-store-919af',
    authDomain: 'book-store-919af.firebaseapp.com',
    storageBucket: 'book-store-919af.firebasestorage.app',
    measurementId: 'G-4E4P27MKBV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADVGEZKK4GzOcQ010S3WAgGwgrOU-q4D0',
    appId: '1:1017556164170:android:68c113d03a4d91bd3b10b3',
    messagingSenderId: '1017556164170',
    projectId: 'book-store-919af',
    storageBucket: 'book-store-919af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADIXMZsFQoRNwZWgiGkgIrLNPNnKXIYxc',
    appId: '1:1017556164170:ios:c507939766e3fb563b10b3',
    messagingSenderId: '1017556164170',
    projectId: 'book-store-919af',
    storageBucket: 'book-store-919af.firebasestorage.app',
    iosBundleId: 'com.example.booklyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADIXMZsFQoRNwZWgiGkgIrLNPNnKXIYxc',
    appId: '1:1017556164170:ios:c507939766e3fb563b10b3',
    messagingSenderId: '1017556164170',
    projectId: 'book-store-919af',
    storageBucket: 'book-store-919af.firebasestorage.app',
    iosBundleId: 'com.example.booklyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkp80OWvDjT5izvKBJwtbSJ_4cnRKrhEU',
    appId: '1:1017556164170:web:9c7769aeb6becf863b10b3',
    messagingSenderId: '1017556164170',
    projectId: 'book-store-919af',
    authDomain: 'book-store-919af.firebaseapp.com',
    storageBucket: 'book-store-919af.firebasestorage.app',
    measurementId: 'G-XFCP1PCZ14',
  );
}
